management:
  endpoints:
    web:
      exposure:
        include: "*" #may be "health,info,prometheus"
  metrics:
    tags:
      application: 'demo-micrometer'
spring:
  application:
    name: demo-micrometer
  task:
    scheduling:
      pool:
        size: 2
  datasource:
    url: jdbc:postgresql://localhost:5432/local_db
    username: user
    password: password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: none